name: mlflow-telco-churn-env

channels:
  - conda-forge

dependencies:
  - python=3.12.7
  - pip<=24.2
  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - cloudpickle
